# Generated by Django 4.2.30 on 2026-06-13 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('label', models.CharField(choices=[('REAL', 'Real'), ('FAKE', 'Fake'), ('UNCERTAIN', 'Uncertain')], max_length=10)),
                ('confidence', models.FloatField(help_text='Confidence % of predicted class')),
                ('real_probability', models.FloatField(help_text='P(Real) as percentage')),
                ('fake_probability', models.FloatField(help_text='P(Fake) as percentage')),
                ('frames_analyzed', models.IntegerField(default=0)),
                ('face_grid_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processing_time', models.FloatField(blank=True, help_text='Inference time in seconds', null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prediction Record',
                'verbose_name_plural': 'Prediction Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
