# Generated by Django 4.2.30 on 2026-06-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='gradcam_grid_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
