# Generated by Django 4.2.30 on 2026-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_predictionrecord_gradcam_grid_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='detection_mode',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', help_text="'video' = full temporal analysis, 'image' = single-frame fallback", max_length=10),
        ),
    ]
