# Generated by Django 4.2.30 on 2026-06-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_predictionrecord_detection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='frame_timeline',
            field=models.JSONField(blank=True, help_text='Cumulative-prefix fake-probability timeline for video mode. Null for image mode.', null=True),
        ),
    ]
