# Generated by Django 4.2.30 on 2026-06-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_predictionrecord_frame_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionrecord',
            name='frame_timeline',
        ),
    ]
